# -*- coding: utf-8 -*-
"""ren.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1g-70DE8nPyrtMpqQFzMCPzi-CGwcUhmZ
"""

import csv
import pprint

#全ての情報を格納したリストl_penを作る
with open('/content/data.csv') as f:
    reader = csv.reader(f)
    l_pen = [row for row in reader]

#yの加速度だけ格納したリストl_yを作る
l_y = []
for i in range(len(l_pen)):
  l_y.append(l_pen[i][2])

for idx in range(len(l_pen)):
  if l_pen[idx][1]==l_pen[idx][2]:
    for i in range(2,51):
      if l_pen[idx+i][1]==l_pen[idx+i][2] and float(max(l_y)) < float(2):
        print('ペン回し検知','経過時間：{}ms'.format(idx*10),'{}ms後にもう一度(xの加速度)=(yの加速度)'.format(i*10))
        break













1212

l_pen[1]

'''
for i in range(len(l_pen)):
  print(l_pen[i][2])

'''



l_pen[0][0]
l_pen[1][3]
#print(len(l_pen))

for idx in range(len(l_pen)):
  if l_pen[idx][1]==l_pen[idx][2]:
    print(l_pen[idx][0])

for idx in range(len(l_pen)):
  if l_pen[idx][1]==l_pen[idx][2]:
    for i in range(10,50):
      if l_pen[idx+i][1]==l_pen[idx+i][2]:
        print('ペン回し検知')

for idx in range(len(l_pen)):
  if l_pen[idx][1]==l_pen[idx][3]:
    print(l_pen[idx][0])

#緑青交差はダメだな。。。

l_y = []
for i in range(len(l_pen)):
  l_y.append(l_pen[i][2])
print(l_y)
print(l_y[1])

print(max(l_y))
min = min(l_y)
print(min)

sorted(l_y)

